#!/usr/bin/python
# -*- coding: utf-8 -*-

### Imports SOAP text content, taking the url as an argument
### USAGE: import_soap url

import sys
import urllib2
import re
from BeautifulSoup import BeautifulSoup

if len(sys.argv) < 2:
	print ("USAGE: import_soap url")
	sys.exit(1)

def parse_soap(url):
        page=urllib2.urlopen(url)
        soup=BeautifulSoup(page.read())

        soap_content=soup.find('div',{'class':'portlet-content'})
        others=soup.findAll('div', {'class':'iportlet-content'})

        # Remove all <br /> tags
        for linebreak in soup.findAll('br'):
                linebreak.extract()

        headers=soup.findAll('p')

	(S,O,A,P) = (None,None,None,None)

        for h in headers:
                if (re.match(u'\[Subjective\]', h.text)):
                        S = h.findNext('div')
                if (re.match(u'\[Objective\]', h.text)):
                        O = h.findNext('div')
                if (re.match(u'\[Assessment\]', h.text)):
                        A = h.findNext('div')
                if (re.match(u'\[Assessment & Plan\]', h.text)):
                        P = h.findNext('div')

	return (S,O,A,P)


(S,O,A,P) = parse_soap(sys.argv[1])

print "Subjective:"
if S:
	for line in S.contents:
		print line

print "Objective:"
if O:
	for line in O.contents:
		print line

print "Assessment:"
if A:
	for line in A.contents:
		print line

print "Plan:"
if P:
	for line in P.contents:
		print line
