#!/usr/bin/python
# -*- coding: utf-8 -*-

### This script will grab EMR text information and feed it into MySQL database.
### Manually navigate to EMR to login and obtain magic string

import mechanize
import re
import sys
import urllib2
from BeautifulSoup import BeautifulSoup 
import MySQLdb

magicstr='(S(ybe0g1qxcoxpzm45cxqqkjfd))'
start_date='2014-01-25'
end_date='2014-12-31'

if len(sys.argv) < 2:
	print ("USAGE: import_encounters 00000000")
	sys.exit(1)

def parse_title(title):
	### Returns date and type parsed from title. Date of last day of admission are returned in case of IPD records.

#	pattern = re.compile("^\((.*)\)(20[0-9\/]*)&nbsp;(.*)&nbsp;(.*)$")
	pattern_type = re.compile("^\((.*)\)")
	pattern_opd = re.compile("(20[0-9\/]*)&nbsp;(.*)&nbsp;(.*)$")
	pattern_ipd = re.compile("(20[0-9\/]*)[\s-]+(20[0-9\/]*)&nbsp;(.*)&nbsp;(.*)$")
	
	type_c = pattern_type.match(title).group(1)

	if (type_c == u"門診"):
		# OPD record parsing
		type="OPD"
		result = pattern_opd.search(title)

		if result:
			return (result.group(1), type)
		else:
			# Cannot parse!
		        print 'No match'

	elif (type_c == u"住院" or type_c == u"急診"):
		# IPD record parsing
		if type_c == u"住院":
			type="IPD"
		else:
			type="ER"

                result = pattern_ipd.search(title)

                if result:
					return (result.group(2), type)
                else:
                        # Cannot parse!
                        print 'No match'

	elif (type_c == u"住院中"):
		# Currently under admission; ignore
		# Ignore
		type='Adm'
	else:
		print "Unable to parse title type!"
		type="Undefined"
	return None

db = MySQLdb.connect(host="localhost", port=3306, user="cakephp", passwd="cakephp", db="cakephp", charset='utf8')
cursor = db.cursor()

url_a='http://hisweb.hosp.ncku/Emrquery/' + magicstr + '/tree/list.aspx?chartno='
url_z='&start=' + start_date + '&stop=' + end_date + '&query=0'

mrd=sys.argv[1]
url=url_a + mrd + url_z

print "Locating directory at "+url

page=urllib2.urlopen(url)
soup=BeautifulSoup(page.read())
events=soup.find('li',{'id':'emr'}).ul

encounter=events.findChildren('li', recursive=False)

for enc in encounter:
	enctext=enc.a.text
	enclink=enc.a.get('href')

	print "Processing encounter: " + enctext

	(date, type) = parse_title(enctext)
#	date_filename=mrd+"/"+date[0:4]+date[5:7]+date[8:10] # Remove '/', turn into YYYYMMDD format
	link = 'http://hisweb.hosp.ncku/Emrquery/' + magicstr + '/tree/'+enclink

	# Get the raw HTML from the extracted link
	EMRreader=mechanize.Browser()
	response=EMRreader.open(link)
	htmldata=unicode(response.read(), "utf-8")

	print "Fetching data from: " + link + " ..."

	### Brrrr, Unicode troubles
	cursor.execute("INSERT INTO `cakephp`.`encounters` (`title` , `date`, `patient_id`,`content`,`user_id`) VALUES (%s, %s, %s, %s, %s)",(enctext, date, mrd, htmldata,'1'))
	print

print "== Commiting to database =="
try:
	db.commit()
except:
	db.rollback()

print "Encounter import complete!"
db.close()
	

